# Generated by Django 3.1.4 on 2020-12-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='updated',
        ),
        migrations.AddField(
            model_name='photo',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
